apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-and-test-pipeline-run
spec:
  pipelineRef:
    name: git-clone-and-test-pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  params:
    - name: repo-url
      value: https://github.com/TeraSky-OSS/java-sample-app.git